# Generated by Django 6.1 on 2026-09-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='activation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
