# Generated by Django 6.1 on 2026-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffprofile_activation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
