# Generated by Django 6.1 on 2026-09-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0002_alter_tablebooking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to='orders.order'),
        ),
    ]
