# Generated by Django 6.1 on 2026-09-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0003_tablebooking_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_booking', to='orders.order'),
        ),
    ]
